services:
  webapi:
    image: giveaway-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/etc/letsencrypt/live/giveawayproject.jettonetto.org/fullchain.pem
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__KeyPath=/etc/letsencrypt/live/giveawayproject.jettonetto.org/privkey.pem
    ports:
      - "8081:8081"
      - "8080:8080"
    volumes:
      - /etc/letsencrypt/live/giveawayproject.jettonetto.org:/etc/letsencrypt/live/giveawayproject.jettonetto.org
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
  