services:
  webapi:
    image: giveaway-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8443
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/etc/letsencrypt/archive/giveawayproject.jettonetto.org/fullchain1.pem
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__KeyPath=/etc/letsencrypt/archive/giveawayproject.jettonetto.org/privkey1.pem
      - ASPNETCORE_Kestrel__Endpoints__Https__Url=https://0.0.0.0:443
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://0.0.0.0:80
      - ASPNETCORE_HOSTNAME=giveawayproject.jettonetto.org
      - ASPNETCORE_GiaoHangNhanh__ApiToken=${GHN_API_TOKEN}
      - Jwt__JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - Jwt__JWT_ISSUER=giveawayapi.com
      - Jwt__JWT_AUDIENCE=giveaway.com
      - Jwt__JWT_TOKEN_EXPIRE_TIME_IN_MINUTES=43200
      - Google__ClientId=${GOOGLE_CLIENT_ID}
      - Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
      - ConnectionStrings__DefaultDB=${DEFAULT_DB_CONNECTION_STRING}
      - MailSettings__Mail=${MAIL_SETTINGS_MAIL}
      - MailSettings__DisplayName=GIVEAWAY
      - MailSettings__Password=${MAIL_SETTINGS_PASSWORD}
      - MailSettings__Host=smtp.gmail.com
      - MailSettings__Port=587
      - MailSettings__AppDomain=https://giveawayproject.jettonetto.org:8443/api/auth/
      - MailSettings__EmailConfirmation=confirm-email?id={0}&token={1}
      - VNPay__TmnCode=${VNPAY_TMNCODE}
      - VNPay__HashSecret=${VNPAY_HASHSECRET}
      - VNPay__PaymentUrl=${VNPAY_PAYMENTURL}
      - AdminAccount__Email=admin@gmail.com
      - AdminAccount__Password=admin
      - EmailTemplateDirectory=Services/MailTemplate/
      - RedirectDirectory=https://giveawayproject.jettonetto.org/
    ports:
      - "8443:443"
      - "8080:8080"
    volumes:
      - /etc/letsencrypt/live/giveawayproject.jettonetto.org:/etc/letsencrypt/live/giveawayproject.jettonetto.org:ro
      - /etc/letsencrypt/archive/giveawayproject.jettonetto.org:/etc/letsencrypt/archive/giveawayproject.jettonetto.org:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Ho_Chi_Minh:/usr/share/zoneinfo/Asia/Ho_Chi_Minh:ro
    user: "0:0"
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    volumes:
#      - ./grafana:/var/lib/grafana
#    depends_on:
#      - prometheus
