services:
  webapi:
   image: giveaway-api
   build:
     context: .
     dockerfile: Dockerfile
   ports:
    - "8081:8081"
    - "8080:8080"
  volumes:
    - /etc/letsencrypt/live/giveawayproject.jettonetto.org:/etc/letsencrypt/live/giveawayproject.jettonetto.org