name: VPS

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [self-hosted-vps, self-hosted-radriar]
    environment: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
 
    - name: Build
      run: docker compose up --build -d
 
