name: VPS

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [self-hosted-vps]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
 
    - name: Build
      env: 
        GHN_API_TOKEN: ${{ secrets.GIAO_HANG_NHANH_TOKEN }}
      run: docker compose up --build -d
 
